#!/bin/bash


cd MCFM-8.0_original/Bin/
rm W_only_* grid-* input-* input__* log*
echo "============================================================================================================="
echo "|||||||||||||||||||||||>>>>>----------- MCFM-8.0------O-R-I-G-I-N-A-L----------->>>>> |||||||||||||||||||||||"
echo "============================================================================================================="
for creategrid in false #true
do
sed "s/dummy_grid/$creategrid/" <input_dummy.DAT >input__$creategrid.DAT
       for order in lo #nlo nnlo nlocoeff nnlocoeff
       do
       echo "                                                  "
       date
       echo "----------------->>   IN PROCESS: 'creategrid'-.$creategrid. ; 'order'-'$order';  <<------------------"
       sed "s/dummy_order/$order/" <input__$creategrid.DAT >input-$creategrid$order.DAT
       ./mcfm input-$creategrid$order.DAT >log1_$creategrid\_$order
       ./mcfm input-$creategrid$order.DAT  >log2_$creategrid\_$order    
       echo "                                                  "
       sed -e :a -e '$q;N;8,$D;ba' log2_$creategrid\_$order 
       echo "                                                  "
       echo "-----------------<<   DONE!: 'creategrid'-.$creategrid. ; 'order'-'$order';  >>------------------"
       date
       echo "============================================================================================================="
       cd ../../TESTER_RESULTS/mcfm-original
       mkdir TESTER_$creategrid\_$order
       cd -
       mv grid* W_only_* log* input-$creategrid$order.DAT  ../../TESTER_RESULTS/mcfm-original/TESTER_$creategrid\_$order
       done
rm input__$creategrid.DAT
done 

cd ../../MCFM-8.0/Bin/
rm W_only_* grid-* input-* input__* log*
echo "============================================================================================================="
echo "|||||||||||||||||||||||<<<<<----------- MCFM-8.0------M-O-D-I-F-I-E-D-----------<<<<< |||||||||||||||||||||||"
echo "============================================================================================================="
for creategrid in true false
do
sed "s/dummy_grid/$creategrid/" <input_dummy.DAT >input__$creategrid.DAT
       for order in lo #nlo nnlo nlocoeff nnlocoeff
       do
       echo "                                                  "
       date
       echo "----------------->>   IN PROCESS: 'creategrid'-.$creategrid. ; 'order'-'$order';  <<------------------"
       sed "s/dummy_order/$order/" <input__$creategrid.DAT >input-$creategrid$order.DAT
       ./mcfm input-$creategrid$order.DAT >log1_$creategrid\_$order
       ./mcfm input-$creategrid$order.DAT  >log2_$creategrid\_$order
       echo "                                                  "
       sed -e :a -e '$q;N;8,$D;ba' log2_$creategrid\_$order 
       echo "                                                  "
       echo "-----------------<<   DONE!: 'creategrid'-.$creategrid. ; 'order'-'$order';  >>------------------"
       date
       echo "============================================================================================================="
       cd ../../TESTER_RESULTS/mcfm-modified
       mkdir TESTER_$creategrid\_$order
       cd -
       mv grid* W_only_* log* input-$creategrid$order.DAT  ../../TESTER_RESULTS/mcfm-modified/TESTER_$creategrid\_$order
       done
rm input__$creategrid.DAT
done 

cd ../../

exit
