#!/bin/bash


cp mcfm_interface_vecIter.cxx mcfm_interface.cxx

cd ../../MCFM-8.0/Bin/
rm grid*
echo ''
echo '   >>>   compiling mcfm-bridge   <<<   '
echo ''

cd /nfs/dust/cms/user/volinar/tools/Test_AREA/mcfm-bridge-0.0.35
make install
sleep 2
echo ''
echo '   >>>   compiling MCFM-8.0   <<<   '
echo ''

cd ../MCFM-8.0

make

cd Bin
sleep 2
./mcfm input.DAT
#./mcfm input.DAT

root -l *.root

exit 0

